version: '3.7'

services:
  app:
    image: node:lts
    networks:
      - traefik_proxy
      - default
    working_dir: /var/www/html/app/
    command: yarn preview --port 8000 --host
    volumes:
      - ./:/var/www/html/app
    labels:
      - traefik.enable=true
      - traefik.http.routers.work-202203__${PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.work-202203__${PROJECT_NAME}.rule=Host(`${PROJECT_NAME}.demo.beeclover.pro`)
      - traefik.http.routers.work-202203__${PROJECT_NAME}.tls.certresolver=leresolver
      - traefik.http.services.work-202203__${PROJECT_NAME}.loadbalancer.server.port=8000
      # - traefik.http.routers.work-202203__${PROJECT_NAME}.middlewares=basic-auth@file

networks:
  traefik_proxy:
    external: true
