version: "3.7"

services:
  app:
    env_file:
      - ./.env
    image: php:8.1-apache
    volumes:
      - .:/var/www/html
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
      labels:
        - traefik.enable=true
        - traefik.http.routers.work-202203__${PROJECT_NAME}.entrypoints=websecure
        - traefik.http.routers.work-202203__${PROJECT_NAME}.rule=Host(`${PROJECT_NAME}.demo.beeclover.pro`)
        - traefik.http.routers.work-202203__${PROJECT_NAME}.tls.certresolver=leresolver
        - traefik.http.services.work-202203__${PROJECT_NAME}.loadbalancer.server.port=80
        - traefik.http.routers.work-202203__${PROJECT_NAME}.middlewares=basic-auth@file

networks:
  default:
    external:
      name: proxy-main
